export const data = JSON.parse("{\"key\":\"v-438ffe52\",\"path\":\"/demo/markdown.html\",\"title\":\"Markdown Enhance\",\"lang\":\"en-US\",\"frontmatter\":{\"title\":\"Markdown Enhance\",\"icon\":\"markdown\",\"order\":2,\"category\":[\"Guide\"],\"tag\":[\"Markdown\"],\"description\":\"VuePress basically generate pages from Markdown files. So you can use it to generate documentation or blog sites easily.\\nYou should create and write Markdown files, so that VuePress can convert them to different pages according to file structure.\\n\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://docs.visionhub.es/demo/markdown.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Visionhub docs\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Markdown Enhance\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"VuePress basically generate pages from Markdown files. So you can use it to generate documentation or blog sites easily.\\nYou should create and write Markdown files, so that VuePress can convert them to different pages according to file structure.\\n\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"og:locale:alternate\",\"content\":\"es-ES\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Markdown\"}],[\"link\",{\"rel\":\"alternate\",\"hreflang\":\"es-es\",\"href\":\"https://docs.visionhub.es/es/demo/markdown.html\"}]]},\"excerpt\":\"<p>VuePress basically generate pages from Markdown files. So you can use it to generate documentation or blog sites easily.</p>\\n<p>You should create and write Markdown files, so that VuePress can convert them to different pages according to file structure.</p>\\n\",\"headers\":[{\"level\":2,\"title\":\"Markdown Introduction\",\"slug\":\"markdown-introduction\",\"link\":\"#markdown-introduction\",\"children\":[]},{\"level\":2,\"title\":\"Markdown Config\",\"slug\":\"markdown-config\",\"link\":\"#markdown-config\",\"children\":[]},{\"level\":2,\"title\":\"Markdown Extension\",\"slug\":\"markdown-extension\",\"link\":\"#markdown-extension\",\"children\":[{\"level\":3,\"title\":\"VuePress Enhancement\",\"slug\":\"vuepress-enhancement\",\"link\":\"#vuepress-enhancement\",\"children\":[]},{\"level\":3,\"title\":\"Theme Enhancement\",\"slug\":\"theme-enhancement\",\"link\":\"#theme-enhancement\",\"children\":[]}]},{\"level\":2,\"title\":\"Slide 1\",\"slug\":\"slide-1\",\"link\":\"#slide-1\",\"children\":[]},{\"level\":2,\"title\":\"Slide 2\",\"slug\":\"slide-2\",\"link\":\"#slide-2\",\"children\":[]},{\"level\":2,\"title\":\"Slide 3.1\",\"slug\":\"slide-3-1\",\"link\":\"#slide-3-1\",\"children\":[]},{\"level\":2,\"title\":\"Slide 3.2\",\"slug\":\"slide-3-2\",\"link\":\"#slide-3-2\",\"children\":[]}],\"readingTime\":{\"minutes\":3.19,\"words\":956},\"filePathRelative\":\"demo/markdown.md\",\"git\":{}}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
